---
- name: Install chrony
  pacman: name=chrony state=present

- name: Install chrony networkmanager dispatcher
  command: /usr/bin/aura -Ax --noconfirm --needed networkmanager-dispatcher-chrony
  tags:
    - aura
    - networkmanager

- name: Push chrony configuration file
  copy: src=chrony.conf dest=/etc/chrony.conf
  notify:
    - restart chrony

- name: Enable and start chrony
  service: name=chronyd.service enabled=yes state=started
