---
- name: Manjaro Awesome Workstation Playbook
  hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: aura, tags: ['aura'] }
    - { role: terminals, tags: ['terminals'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }
    - { role: pass, tags: ['pass'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: unbound, tags: ['unbound'] }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: udisks, tags: ['udisks'] }
    - { role: spell, tags: ['spell'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: media, tags: ['media'] }
    - { role: mpd, tags: ['mpd'] }
    - { role: mpv, tags: ['mpv'] }
    - { role: pianobar, tags: ['pianobar'] }
    - { role: screensaver, tags: ['screensaver'] }
    - { role: cups, tags: ['cups'] }
    - { role: pdf, tags: ['pdf'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: hashicorp, tags: ['hashicorp'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    - { role: borg, tags: ['borg'] }
    - { role: mapping, tags: ['mapping'] }
    - { role: sound, tags: ['sound'] }
    - { role: bluetooth, tags: ['bluetooth'], when: "bluetooth is defined" }
    - { role: hostsctl, tags: ['hostsctl'], when: "hostsctl is defined" }
    - { role: logitech, tags: ['logitech'] }
    - { role: vim, tags: ['vim'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: docker, tags: ['docker'] }
    - { role: menus, tags: ['menus'] }
    - { role: nvm, tags: ['nvm'] }
    - - { role: writing-snaps, tags: [' '] }

  vars_prompt:
    - name: user_password
      prompt: "Enter Password for User Configured During Install"
