---
- name: Install Stow
  pacman:
    name: stow
    state: present
 tags:
   - dotfiles

- name: Install user dotfiles
  script: dotfiles.sh
  become: yes
  become_user: "{{ user.name }}"
 tags:
   - dotfiles
