---
- name: restart paccache
  service:
    name: paccache.timer
    state: restarted

- name: stop systemd per-user instance
  service:
    name: "user@{{ user.uid }}"
    state: stopped

- name: Enable and start Snapd Package Manager
  service:
    name: snapd.service
    enabled: yes
    state: started
