---
- name: Install xdg-user-dirs
  pacman:
   name: xdg-user-dirs
   state: present
  tags:
    - x

- name: Create user directories
  command: /usr/bin/xdg-user-dirs-update
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - x

- name: Install perl-file-mimeinfo
  pacman:
   name: perl-file-mimeinfo
   state: present
  tags:
    - x
