---
- name: Install hostsctl
  command: /usr/bin/aura -Ax --noconfirm --needed hostsctl
  tags:
    - aur
    - hostsctl

- name: Push hostsctl config
  template:
   src: hostsctl.conf.j2
   dest: /etc/hostsctl.conf
  tags:
   - hostsctl

- name: Update hostsctl
  command: hostsctl update
  tags:
   - hostsctl
