---
- name: Install VirtualBox and dependencies
  pacman:
    name:
      - net-tools
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-dkms
      - virt-manager
    state: present

- name: Install VirtualBox extensions
  command: /usr/bin/aura -Ax --noconfirm --needed virtualbox-ext-oracle
  tags:
    - aura

- name: Add the user to vboxusers group
  user: name={{ user.name }} groups=vboxusers append=yes
  tags:
    - user

- name: Install Kimchi
  command: sudo aura -Ax --needed --noconfirm kimchi

- name: Install Barrier
  command: sudo aura -Ax --needed --noconfirm barrier
