---
- name: Install Borg && RClone
  pacman:
    name:
      - python-llfuse
      - borg
      - rclone
    state: present
  tags:
    - borg
- name: Install Vorta
  command: /usr/bin/aura -Ax --noconfirm --needed vorta
  tags:
    - aura
    - borg
