---
- name: Install filesystem packages
  pacman:
    name: "{{ packages.filesystem_packages }}"
    state: present

- name: Install File Managers
  pacman:
    name:
      - doublecmd-qt5
      - ranger
    state: present

- name: Install Polo File Manager
  command: sudo aura -Ax --needed --noconfirm polo-bin

- name: Install Disk Utilities
  pacman:
    name:
      - smartmontools
      - gsmartcontrol
      - gnome-disk-utility
      - gparted
      - rsync
      - rclone
      -



