---
- name: Install filesystem packages
  pacman:
    name: "{{ filesystem_packages }}"
    state: present

- name: Install File Managers
  pacman:
    name:
      - doublecmd-qt5
      - thunar-volman-gtk3
      - thunar
      - thunar-archive-plugin-gtk3
      - ranger
    state: present

- name: Install Disk Utilities
  pacman:
    name:
      - smartmontools
      - gsmartcontrol
      - gnome-disk-utility
      - gparted
      - rsync



