---
- name: Install filesystem packages
  pacman:
    name: "{{ packages.filesystem_packages }}"
    state: present
  tags:
    - filesystems

- name: Install File Managers
  pacman:
    name:
      - doublecmd-qt5
      - ranger
      - manjaro-ranger-settings
    state: present
  tags:
    - filesystems


- name: Install Disk Utilities
  pacman:
    name:
      - smartmontools
      - gsmartcontrol
      - gnome-disk-utility
      - gparted
      - rsync
      - rclone
      - mediainfo
      - pngcrush
      - mutagen
      - trash-cli
    state: present
  tags:
    - filesystems 



