---
- name: Install mpd
  pacman: name=mpd state=present

- name: Install mpc
  pacman: name=mpc state=present


- name: Install mpc
  pacman: name=mpc state=present

- name: Install ncmpcpp
  pacman: name=ncmpcpp state=present

- name: Install Sonata
  pacman: name=sonata state=present

- name: Install LibMPD
  pacman: name=libmpd state=present

