---
- name: Add plugdev group
  group:
      name: plugdev
      state: present
  tags:
   - logitech

- name: Add {{ user.name }} to plugdev group
  user:
      name: "{{ user.name }}"
      groups: plugdev
      append: yes
  tags:
    - user
    - logitech

- name: Install Solaar
  pacman:
      name: solaar
      state: present
  tags:
   - logitech
