---
- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-en_US
    state: present
  tags:
    - spell

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-en
    state: present
  tags:
    - spell
