---
- include: abcde.yml
- include: imagemagick.yml
- include: gimp.yml
- include: gthumb.yml
- include: feh.yml
- include: imv.yml
- include: darktable.yml
- include: qcode.yml
- include: coulr.yml
- include: oomox.yml
- include: gpick.yml
- include: pencilsheep.yml


- name: Install misc media codecs and helpers
  pacman:
    name: "{{ packages.codecs }}"
    state: present

- name: Install Metadata Anonymisation Toolkit
  command: /usr/bin/aura -Ax --noconfirm --needed mat2
  tags:
    - aura
    - mat

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present
