---
- include: abcde.yml
- include: imagemagick.yml
- include: gimp.yml
- include: gthumb.yml
- include: feh.yml
- include: imv.yml
- include: qcode.yml
- include: coulr.yml
- include: oomox.yml
- include: gpick.yml


- name: Install Media Codecs
  pacman:
    name: "{{ packages.codecs }}"
    state: present
  tags:
    - media

- name: Install Metadata Anonymisation Toolkit
  command: /usr/bin/aura -Ax --noconfirm --needed mat2
  tags:
    - aura
    - media

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present
  tags:
    - media

