---
- name: Copy pacman configuration file
  copy: src=pacman.conf dest=/etc/pacman.conf

- name: Refresh pacman mirrors
  pacman: update_cache=yes


- include: shell.yml
- include: user.yml
- include: sudo.yml
- include: packages.yml
- include: journal.yml
